### ISSUE TITLE
Transform Ben's "library" - code into R-package.

### ISSUE THREAD

**Issue by hvwaldow** [fairagro/M4.4_UC6_ARC#4]
* [x] #6 
* [x] #16 
* [x] #13 
* [x] #14 
* [x] #15 
* [x] #21
* [x] #22
* [x] #20

**Comment by aleidel** [comment]
- Release to CRAN not without consent from BL and he still wants to make some changes
-  alternative 1: private github -> install via devtools with github token via devtools::install_github("user/repo", ref = "main", auth_token = Sys.getenv("GITHUBTOKEN")) 
- alternative 2: upload compressed package in this github project and install via download and install.packages("path/to/compressed/file", source = TRUE, repos=NULL)
- if package construction was successful it should be possible to include R package with library(csmTools) in R

**Comment by hvwaldow** [comment]
Yes, I guess CRAN package wasn't intended anyway.

But that we have UC only in a private repo is super annoying, in particular since we want to cooperate with other measures / TAs. Not sure whether you got a "no" from Ben regarding making his repo public. Discussing this and making the UC-repo public is different  issue (#6). @patrick-koenig 

Whether alternative 1 or 2 is more practical, should be decided by you and @JensKrumsieck.

**Comment by JensKrumsieck** [comment]
I did not think about putting it to CRAN. That's a thing benjamin can do if he likes. We just enable him to do so with this issue.
Furthermore i think alternative 1 is the way to go, he/we is/are doing this already with the crop calendars package in the Dockerfile. 

https://github.com/fairagro/m4.4_UC6_cwl_test_1/blob/62174a2d9c97b3a940a0fd0913b69e2bef7834d4/Dockerfile#L23

This needs to be possible with csmTools so you can use its modules without loading the contents of the source files. 

https://github.com/fairagro/m4.4_UC6_cwl_test_1/blob/7051616c5823b61bb03e3eb94ad9e92a56c164e2/scripts/transform.R#L1

side note: does anyone know why the line's contents aren't rendered like here https://github.com/fairagro/m4.4_UC6_cwl_test_1?tab=readme-ov-file#24062024-1700-jk ???

**Comment by aleidel** [comment]
It would be great to have a repository for this if we get his permission and find out what license he prefers (maybe he would also like to make some changes first). 
Overall, Benjamin has built his project using the recommended package structure and is already using roxygen2 comments, which is great. I'm not sure if he wants to export all of his functions, that could be a default option. I have made some minor changes to a few imports and commented out a function call in get_soil_data.R.
There are still some warnings and notes that I need to resolve before it should be available anywhere, but I think I can install the package csmTools locally on my system with install.packages("path/to/compressed/package", source = TRUE, repos=NULL). 
For a github repo you would have to execute use_github and use_read_me_rmd with devtools, but it shouldn't be that complicated (I could test it for a private repo?). Then it would be possible to use it like cropCalendars (if it is public). It would maybe make sense to add tests for the functions at some point

**Comment by JensKrumsieck** [comment]
As far as i can see his repo is public now: https://github.com/fairagro/uc6_csmTools 🎉
![image](https://github.com/fairagro/M4.4_UC6_ARC/assets/4296194/6fd54dc3-577d-4fc0-a2ed-1022cba81bd4)

**Comment by JensKrumsieck** [comment]
I created a new [branch](https://github.com/fairagro/uc6_csmTools/tree/feature/package_management) in BLs Repo called `feature/package_management` to add proper package management tooling, namely `renv`. This turned out crucial for reproducibility, as the `rdwd` package is not pushed to CRAN for patchlevel updates but updates it's data nonetheless. That bug got me for a few hour which was just because of CRAN not installing the latest package. Furthermore DSSATs R packages does not work in the latest version because of writing not working WTH files...
Installation can not be done by `renv::restore()` after clone or pull. --> #13

I did some fixing of functions that were not exported, the `@importFrom` annotations and rerun `roxygen2::roxygenise()` to rebuild the package data. 
The package is now installable using `remote::install_local(".")` or from github using the specified branch and passes all required checks (`devtools::check()`). --> #14

For the sake of reproducibility i added an **optional** `devcontainer` file which installs all requirements on container creation and compiles the DSSAT program.  Turned out you have to also clone the [data repository](https://github.com/DSSAT/dssat-csm-data) for DSSAT to work. This can be done using `install_dssat.sh`. Data explicitly needs to be in the same directory as the dssat executable and the path length is not allowed to surpass 80 characters (LOL!). 
For the system requirements there is also a `install_requirements.sh` - i dont know how this is handled in R usually but i think on linux all R packages come without their system requirements!?
--> #15, #16

The sample pipeline now works in a well defined environment with the limitation of the DSSAT paths still being hardcoded. 

> [!WARNING] 
> A  thing that cost me hours is that the pipeline does not work with the current HEAD of DSSAT, i used the version BL used instead, which seems to work.

https://github.com/fairagro/uc6_csmTools/blob/88fd0fbc99052d72dde18cf7bd0e9370ee6537d3/inst/etl_pipeline_example.R#L563-L573

Furthermore i updated the README with installation notes. A full comparison can be viewed here: https://github.com/fairagro/uc6_csmTools/compare/main...feature/package_management

However BLs script still produces a whole ot of warnings^^
The Script runs multiple minutes (most time consumed for downloading from dwd) which makes the use of workflows, which you can restart e.g. with different paramerters at a specific points quite a good solution. 

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnI4aWJpcTZmMXg5bzMyNGtoMGIyZDd6ZHNuYXA5Z3Y5bDJ2emJmeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/11ISwbgCxEzMyY/giphy.gif)

**Comment by JensKrumsieck** [comment]
Docker container added in https://github.com/fairagro/uc6_csmTools/commit/bea7f7c4f6ad1759b273378dcb27276d98a55887 (#16 )

**Comment by JensKrumsieck** [comment]
CI based integration test now runs in BLs Repo (#10)
https://github.com/fairagro/M4.4_UC6_ARC/issues/10#issuecomment-2260202799
